# Site settings
title: "Creative Coding"
email: jared@jareddonovan.com
description: > # this means to ignore newlines until "baseurl:"
  Teaching Site for DXB211 Creative Coding
#baseurl: "/bbcswebdav/courses/DXB211_19se1/_site" # the subpath of your site, e.g. /blog/
# For deploying to github, use:
baseurl: "/creative-coding"
url: "" # the base hostname & protocol for your site
twitter_username: awarua
github_username:  awarua

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

sass:
    sass_dir: ./assets/css

# plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/