# Site settings
title: Creative Coding
email: jared@jareddonovan.com
description: > # this means to ignore newlines until "baseurl:"
  An Introduction to Programming for Designers
baseurl: "/creative-coding" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: awarua
github_username:  awarua

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

# plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/